pipeline:
  build:	  
    image: maven:3-jdk-8
    commands: 
      - "mvn package -B"
      
  codeCoverage-sonarQube:
    image: aosapps/drone-sonar-plugin:0.8
    quality: OK
    secrets: [ sonar_host, sonar_token ] 
    
  coverage-report:
    image: plugins/codecov
    settings:
      token: 
        from_secret: CODECOV_TOKEN
      
  
