pipeline:
  build:	  
    image: maven:3-jdk-8
    commands: 
      - "mvn package -B"
      - "mvn cobertura:cobertura"
   # after_success:
      - "bash <(curl -s https://codecov.io/bash) -v -f output/coverage"
   
      
  #codeCoverage-sonarQube:
  #  image: aosapps/drone-sonar-plugin:0.8
  #  quality: OK
  #  secrets: [ sonar_host, sonar_token ] 
    
  coverage-report:
    image: plugins/codecov
    environment:
      CODECOV_TOKEN: 31a62b0e-1838-407c-8d27-5bcf065685ff
    #settings:
    #  files:
    #    - *.xml"
    #  paths:
    #    - "output/coverage"
  #  language: java
  #  script: mvn cobertura:cobertura
    
    
    #settings:
    #  token:
    #  token: 31a62b0e-1838-407c-8d27-5bcf065685ff
    #    from_secret: CODECOV_TOKEN
        
      
  
